name: flutter_dapp
description: Flutter DAPP Project with Soldity.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.3.1
  flutter_dotenv: ^5.0.2
  http: ^0.13.0
  provider: ^6.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - ../contract/contract_abi.json
    - assets/
    - .env